#if !canImport(ObjectiveC)
import XCTest

extension AppTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AppTests = [
        ("testAddVersion", testAddVersion),
        ("testFixVersionReport", testFixVersionReport),
        ("testJiraDocumentFromCommits", testJiraDocumentFromCommits),
        ("testJiraErrors", testJiraErrors),
        ("testReleaseType", testReleaseType),
        ("testVersion", testVersion),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AppTests.__allTests__AppTests),
    ]
}
#endif
